mkdir Bondi
cd Bondi
mkdir V2
cd V2
wget https://github.com/HttpAnimation/Bondi/raw/main/V2/Bondi.sh
wget https://github.com/HttpAnimation/Bondi/raw/main/V2/Games.ini
wget https://github.com/HttpAnimation/Bondi/raw/main/V2/subsections.ini
cd ../
cd ../